name: expenses_100
description: Flutter project.
publish_to: 'none'
version: 1.1.4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  date_format: ^2.0.7
  expandable: ^5.0.1
  flutter_awesome_calculator: ^1.0.0+1
  flutter_form_builder: ^9.3.0
  flutter_slidable: ^3.1.0
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  line_icons: ^2.0.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.webp"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-ExtraLight.ttf
        - asset: assets/fonts/Lato-Thin.ttf